version: '3.8'
services:
  atlas-mysql:
    image: mysql:8.0.30
    platform: linux/x86_64
    volumes:
      - ./config/mysql:/etc/mysql/conf.d

    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=atlas
      - MYSQL_USER=atlas
      - MYSQL_ROOT_PASSWORD=atlas
      - MYSQL_PASSWORD=atlas

    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password